### ISSUE TITLE
GaussSuppression

### ISSUE THREAD

**Issue by sstww** [statisticsnorway/GaussSuppression#52]
I am very much interested in your GaussSuppression project. I am currently using the sdcTable package for tabular data suppression. While the package does its job, it is difficult to set up and take a lot of time to compute.  Could you tell me where you are on your project and what are the advantages of your project comparing with the sdcTable package?

Thanks,
Mark

**Comment by olangsrud** [comment]
The [GaussSuppression](https://cran.r-project.org/package=GaussSuppression) package has become a standard tool at Statistics Norway and it is developed in parallel with applications where it is being used. Right now, we are making wrapper functions for the various types of applications. This will make the package easier to use. Eventually, we will also produce more text that explains its use. This will be seen in future versions of the package.

A presentation can be seen [here](https://github.com/sdcTools/UserSupport/blob/master/docs/W2022/S1_P2_02_Langsrud_Lupp_Bovestad_handout_pdf_version_GaussSuppression_An_R_package_for_Tabular_Data_Suppression.pdf) and the corresponding abstract can be found [here](https://github.com/sdcTools/UserSupport/blob/master/docs/Abstracts_W2022.pdf). 

The suppression algorithm was first implemented in the [easySdcTable](https://cran.r-project.org/package=easySdcTable) package. One reason for introducing Gauss in easySdcTable is that sdcTable applications with linked tables turned out not to work. See [here.](https://htmlpreview.github.io/?https://github.com/statisticsnorway/easySdcTable/blob/master/comparison/ProtectTableTest_2023-01-04.html)

The functionality in easySdcTable is limited and the package GaussSuppression is much more general.
